# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(400, 222)
        self.label = QtWidgets.QLabel(StartWindow)
        self.label.setGeometry(QtCore.QRect(40, 20, 321, 51))
        self.label.setStyleSheet("font: 20pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_login = QtWidgets.QPushButton(StartWindow)
        self.pushButton_login.setGeometry(QtCore.QRect(70, 130, 75, 41))
        self.pushButton_login.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_register = QtWidgets.QPushButton(StartWindow)
        self.pushButton_register.setGeometry(QtCore.QRect(250, 130, 75, 41))
        self.pushButton_register.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.pushButton_register.setObjectName("pushButton_register")

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "聊天系统"))
        self.label.setText(_translate("StartWindow", "欢迎来到聊天系统！"))
        self.pushButton_login.setText(_translate("StartWindow", "登录"))
        self.pushButton_register.setText(_translate("StartWindow", "注册"))
